codecov:
  token: 8182df94-d89b-4855-a672-9351f130e719
  notify:
    require_ci_to_pass: yes
    
cat codecov.yml | curl --data-binary @- https://codecov.io/validate

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
