dist: trusty

sudo: required

language: python

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 
    token:
      secure: #how to get encrypted token from Travis?

before_install:
  - sudo pip install codecov
  
script:
  - coverage run mytan.py
  - codecov
  - sonar-scanner

after_success:
  - codecov
