sudo: required

language: python

dist: trusty

before_install:
  - sudo pip install codecov
  
after_success:
  - codecov

script:
  - coverage run mytan.py
  - codecov
  - sonar-scanner
  
 addons:
  sonarqube:
    organization: "laurelmcintyre-github" 
    token:
      secure: •••••••••••••••• 
