dist: trusty

sudo: required

language: python

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 

before_install:
  - sudo pip install codecov
  - sudo pip install nose
  
script:
  - nosetests --with-coverage mytan
  - coverage run main.py 42
  - codecov
  - sonar-scanner

