dist: trusty

sudo: required

group: edge

language: python

python:
  - "2.7"
  - "3.2"

services:
  -docker

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 

before_install:
  - sudo pip install nose2
  
#install: pip install -r requirements.txt

script:
  - nose2 --with-coverage mytan
  - coverage run mytan.py 42
  - codecov
  - sonar-scanner
 # - bundle exec rake test

after_success: |
  if [ -n "$GITHUB" ]; then
    cd "$TRAVIS_BUILD_DIR"
    pydoc -w $TRAVIS_BUILD_DIR
    mkdir docs
    mv *.html docs/.
    cd docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f https://laurelmcintyre:$GITHUB@github.com/laurelmcintyre/python-ci gh-pages 
  fi
