dist: trusty

sudo: required

group: edge

language: python

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 

before_install:
  - sudo pip install codecov
  - sudo pip install nose2
  
script:
  - nose2 --with-coverage mytan
  - coverage run mytan.py 42
  - codecov
  - sonar-scanner
  - pydoc -w $PWD

#after_success: |
#  if [ -n "$GITHUB_API_KEY" ]; then
#    cd "$TRAVIS_BUILD_DIR"
    ## This generates a `web` directory containing the website.
  #  make web
   # cd web
    #git init
    #git checkout -b gh-pages
  #  git add .
  #  git -c user.name='travis' -c user.email='travis' commit -m init
   # # Make sure to make the output quiet, or else the API token will leak!
    ## This works because the API key can replace your password.
   # git push -f -q https://<me>:$GITHUB_API_KEY@github.com/<me>/<myrepo>-gh-pages gh-pages &2>/dev/null
   # cd "$TRAVIS_BUILD_DIR"
 # fi
