dist: trusty

sudo: required

language: python

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 

before_install:
  - sudo pip install codecov
  - sudo pip install nose2
  
script:
  - nose2 --with-coverage mytan
  - coverage run mytan.py 42
  - codecov
  - sonar-scanner

