group: edge

dist: trusty

sudo: required

language: python

python:
  - "2.7"
  - "3.2"

services:
  -docker
  
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=laurelmcintyre/python-ci

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 

before_install:
 - docker build -t $REPO:$COMMIT -t $REPO:latest .
 
install:
  - sudo -H pip install nose2
  - sudo -H pip install codecov

script:
  - nose2 --with-coverage mytan
  - coverage run mytan.py 42
  - codecov
  - sonar-scanner
  - docker run -it $REPO:$COMMIT /bin/bash -c "cd python-ci"

after_success: |
  if [ -n "$GITHUB" ]; then
    cd "$TRAVIS_BUILD_DIR"
    pydoc -w $TRAVIS_BUILD_DIR
    mkdir docs
    mv *.html docs/.
    cd docs
    cp ../README.md . 
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f https://laurelmcintyre:$GITHUB@github.com/laurelmcintyre/python-ci gh-pages 
  fi

