dist: trusty

sudo: required

group: edge

language: python

python:
  - "2.7"
  - "3.2"

services:
  -docker

addons:
  sonarqube:
    organization: "laurelmcintyre-github" 

before_script:
  - cd "$VERSION"
  - image="$(awk '$1 == "FROM" { print $2; exit }' onbuild/Dockerfile)${VARIANT:+-$VARIANT}

before_install:
  - sudo -H pip install nose2
  - sudo -H pip install codecov

script:
  - nose2 --with-coverage mytan
  - coverage run mytan.py 42
  - codecov
  - sonar-scanner
   - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"
  - true && [ "$VARIANT" ] || travis_retry docker build -t "${image}-onbuild" onbuild

after_success: |
  if [ -n "$GITHUB" ]; then
    cd "$TRAVIS_BUILD_DIR"
    pydoc -w $TRAVIS_BUILD_DIR
    mkdir docs
    mv *.html docs/.
    cd docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f https://laurelmcintyre:$GITHUB@github.com/laurelmcintyre/python-ci gh-pages 
  fi
  
after_script:
- docker images
